services:
  backend:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    networks:
      - net
  chroma:
    image: ghcr.io/chroma-core/chroma:0.6.3
    env_file:
      - ./.env_chroma
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - 8000:8000
    networks:
      - net

volumes:
  index_data:
    driver: local
  backups:
    driver: local

networks:
  net:
    driver: bridge
